var header = document.querySelector('h1');
console.log('$header', header);
console.dir(header);
var explanation = document.querySelector('#explanation');
console.log('$explanation', explanation);
console.dir(explanation);
var hint = document.querySelector('.hint');
console.log('$hint', hint);
console.dir(hint);
var allP = document.querySelectorAll('p');
console.log('$paragraphs', allP);
var exampleLinks = document.querySelectorAll('.example-link');
console.log('$links', exampleLinks);
